### ISSUE TITLE
[1.15.2] Build from 06/12. Golem ignores chests. 

### ISSUE THREAD

**Issue by Geethebluesky** [daPoseidonGuy/strawgolem#1]
Copied from Curseforge.

The golem just wanders around and ignores the chest entirely:
 
[Screenshot](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fi.imgur.com%252fNtpyElJ.png)

The 2 chests in that screenshot are 1 Oak chest from Quark mod (left), and 1 Minecraft original chest (right). Neither seems to appeal to the little guy.

On Forge 31.1.88
No crash, let me know what other info you might need!

**Comment by daPoseidonGuy** [comment]
Ok - so I realized that my implementation wouldn't see modded chests - that should be fixed for the next build - as to why its ignoring the vanilla chest in this case - I don't know

**Comment by daPoseidonGuy** [comment]
Just in case - try this build see if it works:

https://drive.google.com/file/d/1PpqtS0u2U_5KEDBKsue0moaFyvJDxlcZ/view?usp=sharing

**Comment by Geethebluesky** [comment]
Sorry, still no change. Poor thing gets stuck on half-slabs I have over my water channels as well and just stops doing anything.

They can also go through closed fences and jump on top of fences, even... I have screenshots. Are those intentional by any chance?

**Comment by daPoseidonGuy** [comment]
Hmmm. Can't say they are. I've still been unable to replicate the issue with the chests.

Perhaps if I had a copy of the world save?

I'll see if I can replicate these new issues.

As is I'm using the near-exact same system (with improvements to allow it to harvest stem grown blocks) as the old mod for the harvest AI goal, and an extremely similar system for the delivery AI goal.

Perhaps I should switch to a new implementation for these tasks..

**Comment by WenXin20** [comment]
I've run into the same problem when testing my modpack on a server.

When I first spawn a golem, it harvests the crops and places it in a nearby chest, modded or vanilla, but then by the time a new crop grows, it seems to forget that a chest is nearby and just holds the item.

**Comment by daPoseidonGuy** [comment]
Now I've tested this quite a bit and haven't really been able to reproduce - however I always do notice sometimes the golems do wander for longer than I'd like before delivering the item 

I've already committed a fix for this - golems now should deliver to a chest (if they can find it) basically immediately after they pick up a crop.

Perhaps that will resolve this issue as well.

I'm also investigating an issue / improvements for the way I detect if certain blocks are "reachable", that could end up helping as well.

**Comment by WenXin20** [comment]
That might be it, I did notice that one of the golems eventually delivered to a chest, but it took maybe 10 minutes or so before it did, even though it was right next to the chest. 
Another golem that was next to it didn't find that chests though, even though it was spawned and harvested at the same time.

**Comment by daPoseidonGuy** [comment]
> That might be it, I did notice that one of the golems eventually delivered to a chest, but it took maybe 10 minutes or so before it did, even though it was right next to the chest.
> Another golem that was next to it didn't find that chests though, even though it was spawned and harvested at the same time.

https://drive.google.com/file/d/1RFH1VQ6ti84FQGQyfP1Sed79HVHCg3Q1/view?usp=sharing

Try this and see if its better?

**Comment by WenXin20** [comment]
It seems to be better. The first few golems recognized the chest and immediately put the crops in the chest, but after creating new golems and more crops grew and then were harvested, they just stood in that spot for a while. And didn't recognize any chests, even newly placed.

**Comment by daPoseidonGuy** [comment]
Okay - so from testing I see the problem arises with the method responsible for finding the block to move to, which is actually vanilla code.

The further solution I am attempting is having golems "remember" chests they'd used previously so it doesn't have to search for a chest each time it tries to start the delivery goal

Will update this comment with results when I have them

**Comment by daPoseidonGuy** [comment]
Try this to verify if the issue is fixed:
https://drive.google.com/file/d/1-M07pNtq61W43A4phJUeCeYzkFeiQZ1T/view?usp=sharing

**Comment by Geethebluesky** [comment]
I tried your last Dropbox build. The golem still stalls after depositing a few carrots in the chest I have next to the stone stairs.

I remade the farm to get rid of all the half-slabs because they seemed to get him stuck, but that wasn't the problem; he's just standing in the middle of the field with a carrot in hand, perpendicular to the chests in my screenshot from a few days ago, and doesn't move.

Sometimes when I bump into him, he'll take notice of the chest and go deposit, but otherwise he's pretty much holding on to his carrot.

**Comment by Geethebluesky** [comment]
Not sure if this is the way you want to go, but how much work would it be to assign a chest to the golem?

Two other mob-farmer mods (Thaumcraft, Rats) have a mechanism like that, where an item is used to connect or "assign" a mob to a specific chest. Would solve the issue with things being visually in the way?

**Comment by daPoseidonGuy** [comment]
Are you sure you're using the latest dropbox build? I verified myself that the getting stuck on farmland issue no longer occurs and would be very surprised that it is still occuring on your machine.
And by verified, I mean I literally left a LAN world running for an hour and they were still efficiently gathering and delivering crops.

@WenXin20 perhaps you could confirm?

I don't really want to sacrifice the simplicity of the current way it is, but I could add that as an option for players who are so inclined, it wouldn't be much work given that I already added memory for chests.

**Comment by WenXin20** [comment]
I didn't notice them getting stuck on farmland, but I think @Geethebluesky said they were getting stuck on half slabs, which I haven't tried yet. I'll check again to be sure

**Comment by daPoseidonGuy** [comment]
> I didn't notice them getting stuck on farmland, but I think @Geethebluesky said they were getting stuck on half slabs, which I haven't tried yet. I'll check again to be sure

And this is with the newest build (for no getting stuck on farmland?)

That would corroborate what I'm seeing, but I suppose I could add the feature of "prioritizing" a chest somehow. Not sure what implementation would best "fit" the theme of the mod for that though

I've also been porting the mod to fabric which is taking more time than I'd like

**Comment by WenXin20** [comment]
Newest build, yes, but I will need to check again to be sure. I only tilled a few grass blocks into farmland, so they weren't walking on it a lot.

**Comment by WenXin20** [comment]
They are walking normally on farmland and half slabs for me. 
I've also noticed that when the golems
 Is first summoned, it will immediately harvest, but after that it can take quite a while before noticing that another crop is fully grown, even if there are several.

**Comment by daPoseidonGuy** [comment]
> They are walking normally on farmland and half slabs for me.

Okay good, so I'll consider that issue (which is what this thread is for) to be fixed.

> Is first summoned, it will immediately harvest, but after that it can take quite a while before noticing that another crop is fully grown, even if there are several.

This I've noticed, and its simply down to the wandering AI task executing before they have a chance to find a crop.

Now I do like them wandering but I would like it to last less long. I'll investigate ways to improve that after I finish porting to fabric :)

**Comment by Geethebluesky** [comment]
Like I said in my last comment, I removed all the half-slabs from my farm to see if that was the problem or not. It didn't help.

I just redownloaded the file you provided on June 16 at 2am MDT with this link, to make triply sure:
https://drive.google.com/file/d/1-M07pNtq61W43A4phJUeCeYzkFeiQZ1T/view?usp=sharing

Little guy is now holding onto a potato, sitting on top of the block I put above the water square, and staring into the distance. (I think the poor thing has PTSD from his difficult past being gnawed on by filthy rats.)

After I pushed him, he went to deposit the tato in the chest nearby. Now he's standing on top of the chest and again staring into the distance. I want to give him a hug and a cigarette.

**Comment by daPoseidonGuy** [comment]
The next build will have the ability to set a priority chest.

This issue doesn't seem to occur at all on latest builds anymore, either.

So I'm considering the issue closed. Keep an eye for the next release, there's a lot of new stuff :)

**Comment by WenXin20** [comment]
Hello, I've noticed that if there is a chest in the ground (surrounded by farmland on all 4 sides), the golem will walk up to the chest, but then get stuck holding the item.
